services:  # コンポースするサービスたち

    go-api-srv:  # サービスの名前
        container_name: go-api # コンテナ名
        build:  # ビルド設定
            context: ./go-api  # ビルドプロセスが実行されるパス
            dockerfile: Dockerfile  # Dockerfileのパス
        environment: # 環境変数
            TZ: ${TZ}
        tty: true # コンテナ内で対話的操作を可能

    mysql-db-srv: # サービスの名前
        container_name: mysql-db # コンテナ名
        image: mysql:latest  # pullするイメージ
        volumes: # ボリュームの保持。
            - ./mysql-db/db_data:/var/lib/mysql
        environment: # 環境変数
            TZ: ${TZ}
        env_file: # 環境変数のまとまりをファイルに記述して渡す
            - .env.mysql-db-srv
        restart: always  # コンテナの再起動

